services:
  flask-todo-web:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    environment:
      SQLALCHEMY_HOST: flask-todo-db
      SQLALCHEMY_PORT: "5432"
      SQLALCHEMY_DB: flask-demo
      SQLALCHEMY_USER: flask-demo
      SQLALCHEMY_PASSWORD: flask-demo
      PYTHONUNBUFFERED: "True"
    ports:
    - "5050:5050"
    depends_on:
    - flask-todo-db

  flask-todo-db:
    image: postgres:14.20
    environment:
      POSTGRES_USER: flask-demo
      POSTGRES_PASSWORD: flask-demo
      POSTGRES_DB: flask-demo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U flask-demo"]
      interval: 2s
      timeout: 5s
      retries: 5
